version: "3.8"

services:
  backend:
    build: ./backend
    container_name: sentiment-backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend/model:/app/model
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: sentiment-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend